import { useEffect, useState } from 'react';
import Axios from 'axios';
import Head from 'next/head';
import useSWR from 'swr';

import PostCard from '../components/PostCard';

import { Post } from '../types';

export default function Home() {
	const { data: posts } = useSWR('/posts');
	return (
		<>
			<Head>
				<title>Readit: the frond page of the internet</title>
				<meta name='description' content='Generated by create next app' />
			</Head>
			<div className='container flex pt-4'>
				{/* Posts feed */}
				<div className='w-160'>
					{posts?.map((post: Post) => (
						<PostCard post={post} key={post.identifier} />
					))}
				</div>
				{/* Sidebar */}
			</div>
		</>
	);
}
