import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import useSWR from 'swr';

import PostCard from '../components/PostCard';
import { useAuthState } from '../context/auth';

import { Post, Sub } from '../types';

export default function Home() {
	const { data: posts } = useSWR<Post[]>('/posts');
	const { data: topSubs } = useSWR<Sub[]>('/misc/top-subs');

	const { authenticated } = useAuthState();

	return (
		<>
			<Head>
				<title>Readit: the frond page of the internet</title>
				<meta name='description' content='Generated by create next app' />
			</Head>
			<div className='container flex pt-4'>
				{/* Posts feed */}
				<div className='w-160'>
					{posts?.map((post: Post) => (
						<PostCard post={post} key={post.identifier} />
					))}
				</div>
				{/* Sidebar */}
				<div className='ml-6 w-80'>
					<div className='bg-white rounded'>
						<div className='p-4 border-b-2'>
							<p className='text-lg font-semibold text-center'>
								Top Communities
							</p>
						</div>
						<div>
							{topSubs?.map((sub) => (
								<div
									key={sub.name}
									className='flex items-center px-4 py-2 text-xs border-b'
								>
									<Link href={`/r/${sub.name}`}>
										<a>
											<Image
												src={sub.imageUrl}
												alt='Sub Image'
												width={(6 * 16) / 4}
												height={(6 * 16) / 4}
												className='rounded-full cursor-pointer'
											/>
										</a>
									</Link>
									<Link href={`/r/${sub.name}`}>
										<a className='ml-2 font-bold hover:cursor-pointer'>
											/r/{sub.name}
										</a>
									</Link>
									<p className='ml-auto font-medium'>{sub.postCount}</p>
								</div>
							))}
						</div>
						{authenticated && (
							<div className='p-4 border-t-2'>
								<Link href='/subs/create'>
									<a className='w-full px-2 py-1 rounded-sm blue custom-button'>
										Create Community
									</a>
								</Link>
							</div>
						)}
					</div>
				</div>
			</div>
		</>
	);
}
