import Axios from 'axios';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import PostCard from '../components/PostCard';

import { Post } from '../types';

export default function Home() {
	const [posts, setPosts] = useState<Post[]>([]);

	useEffect(() => {
		Axios.get('/posts')
			.then((res) => setPosts(res.data))
			.catch((err) => console.log(err));
	}, []);
	return (
		<div className='pt-12'>
			<Head>
				<title>Readit: the frond page of the internet</title>
				<meta name='description' content='Generated by create next app' />
			</Head>
			<div className='container flex pt-4'>
				{/* Posts feed */}
				<div className='w-160'>
					{posts.map((post) => (
						<PostCard post={post} key={post.identifier} />
					))}
				</div>
				{/* Sidebar */}
			</div>
		</div>
	);
}
